# CS-577: Deep Learning. Assignment 0

#### Student:             Jorge Gonzalez Lopez
#### CWID:                 A20474413
#### Semester:          Spring 2021

In [1]:
import numpy as np
import math

### Exercise A

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([-1,1,3])

In [3]:
r = 2*a - b

print('1. 2a - b is equal to: ' , r)

1. 2a - b is equal to:  [-2 -1  0]


In [4]:
r = a / np.linalg.norm(a)

print('2. Unit vector in the direction of a = ', r)

2. Unit vector in the direction of a =  [0.26726124 0.53452248 0.80178373]


In [5]:
i = np.array([1,0,0])

r = np.linalg.norm(a)
theta = math.acos(np.inner(a,i)/(np.linalg.norm(a)*np.linalg.norm(i)))
                  
print('3. |a| = ', r , ' , and the angle of a relative to the positive x axis: ', math.degrees(theta), 'º')

3. |a| =  3.7416573867739413  , and the angle of a relative to the positive x axis:  74.498640433063 º


In [6]:
i = np.array([1,0,0])
j = np.array([0,1,0])
k = np.array([0,0,1])

cos_a = np.inner(a,i)/(np.linalg.norm(a)*np.linalg.norm(i))
cos_b = np.inner(a,j)/(np.linalg.norm(a)*np.linalg.norm(j))
cos_c = np.inner(a,k)/(np.linalg.norm(a)*np.linalg.norm(k))

print('4. Direction cosines: cos(a) = ', cos_a , ' , cos(b) = ', cos_b , ' ,cos(c) = ', cos_c )

4. Direction cosines: cos(a) =  0.2672612419124244  , cos(b) =  0.5345224838248488  ,cos(c) =  0.8017837257372732


In [7]:
theta = math.acos(np.inner(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)))

print('5. The angle between the vectors a and b is: ', math.degrees(theta), 'º')

5. The angle between the vectors a and b is:  12.933154491899135 º


In [8]:
r = np.inner(a,b)
r2 = np.inner(b,a)

print('6. ab = ', r, ' and ba = ', r2)

6. ab =  32  and ba =  32


In [9]:
theta = 12.93
r = (np.linalg.norm(a)*np.linalg.norm(b)) * math.cos(math.radians(theta))

print('7. ab using the angle between them = ', r)

7. ab using the angle between them =  32.00040453080565


In [10]:
r = np.inner(a,b)/ np.linalg.norm(a)

print('8. Scalar projection of b onto a = ', r)

8. Scalar projection of b onto a =  8.55235974119758


In [11]:
X = np.array([a,[0,1,0],[0,0,1]])
## I determine the t_2 and t_3 values (0 and -1 respectively) and I calculate the t_1 value to get a zero inner product.
r = np.linalg.solve(X,np.array([0,0,-1]))

print('9. One perpendicular vector to a would be = ', r)

9. One perpendicular vector to a would be =  [ 3.  0. -1.]


In [12]:
a_p = np.array([1,2,3],ndmin = 2)
b_p = np.array([4,5,6], ndmin = 2)

try:
    r = np.dot(a_p,b_p)
except:
    print('10. Shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)')


10. Shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)


In [13]:
X = np.array([a,b,[0,0,1]])
## I determine the t_3 value (1) and I calculate the t_1 and t_2 values to get a zero inner product with a and b.
r = np.linalg.solve(X,np.array([0,0,1]))

print('11. One perpendicular vector to a and b would be = ', r)

11. One perpendicular vector to a and b would be =  [ 1. -2.  1.]


In [14]:
X = np.array([a,b,c]).T

r1 = np.linalg.det(X)

print('12. The determinant of the matrix with the vectors as columns is: ', np.round(r1), '-> linearly dependents.\n')

12. The determinant of the matrix with the vectors as columns is:  0.0 -> linearly dependents.



In [15]:
r = np.outer(a.T,b)
r1 = np.outer(a,b.T)


print('13.\n (a.T)b = \n', r, '\n and a(b.T) = \n', r1)

13.
 (a.T)b = 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]] 
 and a(b.T) = 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### Exercise B

In [16]:
A = np.array([[1,2,3],[4,-2,3],[0,5,-1]])
B = np.array([[1,2,1],[2,1,-4],[3,-2,1]])
C = np.array([[1,2,3],[4,5,6],[-1,1,3]])
d = np.array([1,2,3])

In [17]:
r = 2*A - B

print('1. 2A - B is equal to: \n' , r)

1. 2A - B is equal to: 
 [[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


In [18]:
r = np.matmul(A,B)
r1 = np.matmul(B,A)

print('2.\n AB = \n' , r,'\n BA = \n', r1)

2.
 AB = 
 [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]] 
 BA = 
 [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [19]:
r = (np.matmul(A,B)).T
r1 = np.matmul(B.T,A.T)

print('3.\n (AB).T = \n' , r,'\n (B.T)(A.T) = \n', r1)

3.
 (AB).T = 
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]] 
 (B.T)(A.T) = 
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [20]:
r = np.linalg.det(A)
r1 = np.linalg.det(C)

print('4.|A| = ' , np.round(r),' and |C| = ', np.round(r1))
print('C is a singular matrix')

4.|A| =  55.0  and |C| =  0.0
C is a singular matrix


In [21]:
r = np.matmul(A,A.T)
r1 = np.matmul(B,B.T)

print('5.\n (A.T)A = \n' , r,'\n (B.T)(B) = \n', r1)
print('B rows form an orthogonal set')

5.
 (A.T)A = 
 [[ 14   9   7]
 [  9  29 -13]
 [  7 -13  26]] 
 (B.T)(B) = 
 [[ 6  0  0]
 [ 0 21  0]
 [ 0  0 14]]
B rows form an orthogonal set


In [22]:
r = np.linalg.inv(A)
r1 = np.linalg.inv(B)

print('6.\n A^(-1) = \n' , r,'\n B^(-1) = \n', r1)


6.
 A^(-1) = 
 [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]] 
 B^(-1) = 
 [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [23]:
r = np.linalg.inv(C)

print('7.\n C^(-1) = \n' , r)
print('Note: Very large values as |C| is approximately zero. In theory +- Inf.')

7.
 C^(-1) = 
 [[ 1.20095990e+16 -4.00319967e+15 -4.00319967e+15]
 [-2.40191980e+16  8.00639934e+15  8.00639934e+15]
 [ 1.20095990e+16 -4.00319967e+15 -4.00319967e+15]]
Note: Very large values as |C| is approximately zero. In theory +- Inf.


In [24]:
r = np.dot(A,d)

print('8.\n Ad = \n' , r)


8.
 Ad = 
 [14  9  7]


In [25]:
r = np.matmul(A,d)/np.linalg.norm(d)

print('9.\n Projection of rows from A onto d = \n' , r)


9.
 Projection of rows from A onto d = 
 [3.74165739 2.40535118 1.87082869]


In [26]:
A_T = A.T

r = d[0]*A_T[0]+ d[1]*A_T[1]+d[2]*A_T[2]

print('10.\n Linear combination of the colums of A using the vector d = \n' , r)


10.
 Linear combination of the colums of A using the vector d = 
 [14  9  7]


In [27]:
r = np.linalg.solve(B,d)

print('11.\n Bx = d => x = \n' , np.round(r))


11.
 Bx = d => x = 
 [ 1.  0. -0.]


In [28]:
r = np.linalg.solve(C,d)

print('12.\n Cx = d => x = \n' , np.round(r))
print('Note: C is a singular matrix, so it does not have an inverse. The high numbers can be interpreted as +-Inf.')

12.
 Cx = d => x = 
 [-8.00639934e+15  1.60127987e+16 -8.00639934e+15]
Note: C is a singular matrix, so it does not have an inverse. The high numbers can be interpreted as +-Inf.


### Exercise C

In [29]:
D = np.array([[1,2],[3,2]])
E = np.array([[2,-2],[-2,5]])
F = np.array([[1,2],[2,4]])

In [30]:
r = np.linalg.eig(D)

print('1. \n The eigenvalues of D are: ' , r[0][0], ' and ', r[0][1])
print(' and the normalized eigenvectors are: ' , r[1][:,0], ' and ', r[1][:,1])

1. 
 The eigenvalues of D are:  -1.0  and  4.0
 and the normalized eigenvectors are:  [-0.70710678  0.70710678]  and  [-0.5547002  -0.83205029]


In [31]:
r2 = np.dot(r[1][0],r[1][1])

print('2. \n The dot product between the eigenvectors of D is: ' , r2)

2. 
 The dot product between the eigenvectors of D is:  -0.038461538461538214


In [32]:
r = np.linalg.eig(E)
r2 = np.dot(r[1][:,0],r[1][:,1])

print('3. \n The eigenvalues of E are: ' , r[0][0], ' and ', r[0][1])
print(' and the normalized eigenvectors are: ' , r[1][:,0], ' and ', r[1][:,1])
print('\n The dot product between the eigenvectors of E is: ' , r2)

3. 
 The eigenvalues of E are:  1.0  and  6.0
 and the normalized eigenvectors are:  [-0.89442719 -0.4472136 ]  and  [ 0.4472136  -0.89442719]

 The dot product between the eigenvectors of E is:  0.0


In [33]:
print('4. \n The eigenvectors of E are orthogonal between each other (their inner product is 0)')

4. 
 The eigenvectors of E are orthogonal between each other (their inner product is 0)


In [34]:
r = np.linalg.det(F)

print('5. \n |F| = ' , np.round(r), ' and therefore, it does not have a trivial solution (unique solution when the determinant is 0)')


5. 
 |F| =  0.0  and therefore, it does not have a trivial solution (unique solution when the determinant is 0)


In [35]:
F1 = np.array([F[0], [0,1]])
r1 = np.linalg.solve(F1, np.array([0,1]))
# I determine the value of x_2 (1) and calculate x_1, so that the product is 0
F2 = np.array([F[0], [0,1]])
r2 = np.linalg.solve(F2, np.array([0,3]))
# I determine the value of x_2 (3) and calculate x_1, so that the product is 0

print('6. \n One solution to Fx = 0 is: ', r1, 'and another solution would be: ', r2 )

6. 
 One solution to Fx = 0 is:  [-2.  1.] and another solution would be:  [-6.  3.]


In [36]:
r = np.linalg.det(D)

r1 = np.linalg.solve(D, np.array([0,0]))

print('7. \n |D| = ', np.round(r) , ', so as the determinant is non-zero, it has a trivial solution (unique one)')
print('The trivial solution is: ', r1)

7. 
 |D| =  -4.0 , so as the determinant is non-zero, it has a trivial solution (unique one)
The trivial solution is:  [0. 0.]
